version: '3'
services:
    nginx:
        container_name: ${COMPOSE_PROJECT_NAME}_nginx
        build: ./nginx
        expose:
            - ${NGINX_EXPOSED_PORT}
        networks:
            public_net:
                ipv4_address: ${NGINX_IP}
        environment:
            - HAPROXY_IP=${HAPROXY_IP}
            - HAPROXY_PRIVATE_PORT=${HAPROXY_PRIVATE_PORT}
    haproxy:
        build: ./haproxy
        networks:
            public_net:
                ipv4_address: ${HAPROXY_IP}
        ports:
            - 80:80
        expose:
            - ${HAPROXY_PUBLIC_PORT}
        networks:
            public_net:
                ipv4_address: ${HAPROXY_IP}
        environment:
            - NGINX_IP=${NGINX_IP}
            - NGINX_EXPOSED_PORT=${NGINX_EXPOSED_PORT}
            - HAPROXY_IP=${HAPROXY_IP}
            - HAPROXY_PUBLIC_PORT=${HAPROXY_PUBLIC_PORT}
            - HAPROXY_PRIVATE_PORT=${HAPROXY_PRIVATE_PORT}
networks:
    public_net:
        driver: bridge
        ipam:
            driver: default
            config:
                - subnet: ${NETWORK_SUBNET}